
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-pod
spec:
  selector:
    matchLabels:
      app: database-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database-pod
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          value: "1q2w3e4r@#$" 