apiVersion: v1
kind: Service
metadata:
  name: backend-producer-nodeport
  labels:
    app: backend-producer-nodeport
    service: backend-producer-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      # targetPort: 80
      nodePort: 30010
  selector:
    app: backend-producer-pod